# Training parameters
batch_size: 8
batch_size_val: 8
num_epochs: 16
model_name: deeplab
learning_rate: 0.0001
experiment_name: default_experiment
use_clear_sky: true
random_mask: false
val_random_mask: false
random_rotations: false
cluster: false
num_workers: 0

# Paths
log_dir: data/training_logs
dataset_root: data/datasets/optimized_3

# Weights & Biases logging
use_wandb: true
wandb_project: ir-cloud-segmentation
wandb_entity: elrichgro
