#!/usr/bin/env python3

import os
from argparse import ArgumentParser
from irccam.utils.files import load_yaml_file
from irccam.utils.constants import AVAILABLE_MODELS_FILE
from irccam.inference.predict import predict, save_predictions
from irccam.inference.load_model import load_model

available_models = load_yaml_file(AVAILABLE_MODELS_FILE)
parser = ArgumentParser()
parser.add_argument("input_path", type=str, help="Path to input file")
parser.add_argument("--output_path", type=str, help="Path to save output file(s)")
parser.add_argument(
    "--model", type=str, default="model_1", help="The model to predict with", choices=available_models.keys()
)
parser.add_argument("--limit", type=int, help="Limit the number of predictions to make")

args = parser.parse_args()

assert os.path.isfile(args.input_path), f'Invalid input file: "{args.input_path}"'

model = load_model(args.model)
predictions = predict(model, args.input_path, args.limit)
save_predictions(args.input_path, predictions)
