#!/usr/bin/env python3

import os
from argparse import ArgumentParser
from cloudseg.utils.files import load_yaml_file
from cloudseg.utils.constants import AVAILABLE_MODELS_FILE
from cloudseg.inference.predict import predict, save_predictions
from cloudseg.inference.load_model import load_model

available_models = load_yaml_file(AVAILABLE_MODELS_FILE)
parser = ArgumentParser()
parser.add_argument("input_file", type=str, help="Path to input file")
parser.add_argument("--output_dir", type=str, help="Directory to save output file")
parser.add_argument("--output_file", type=str, help="Name for output file")
parser.add_argument(
    "--model", type=str, default="model_1", help="The model to predict with", choices=available_models.keys()
)
parser.add_argument("--limit", type=int, help="Limit the number of predictions to make")

args = parser.parse_args()

assert os.path.isfile(args.input_file), f'Invalid input file: "{args.input_file}"'

model = load_model(args.model)
predictions = predict(model, args.input_file, args.limit)
save_predictions(args.input_file, predictions, args.output_dir, args.output_file)
